apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: retail-banking-istio-igw
  namespace: retail-banking-team

spec:
  selector:
    istio: ingressgateway

  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - retail-banking.cloud9.ceo

    - port:
        number: 443
        name: https
        protocol: HTTPS

      tls:
        mode: SIMPLE
        credentialName: retail-banking-credential

      hosts:
        - retail-banking.cloud9.ceo